// Apuntes curados de Arquitectura de Software (markdown revisado).
// Fuente: .md de BancoDeInformacion/ArquitecturaDeSoftware/. Se completa por lotes revisados.
const apuntes = [
  {
    id: "AP-ASW-01",
    tema: "POO",
    titulo: "Fundamentos y pilares de la POO",
    contenido: "## ¿Qué es la POO?\n\nLa **Programación Orientada a Objetos (POO)** es un paradigma basado en envolver bloques de información y su comportamiento relacionado en lotes especiales llamados **objetos**. Estos objetos se construyen a partir de un grupo de «planos» definidos por el programador, que se denominan **clases**.\n\n## Los cuatro pilares\n\n### Abstracción\nEs el modelo de un objeto o fenómeno del mundo real, **limitado a un contexto específico**, que representa todos los datos relevantes a ese contexto con gran precisión y **omite el resto**. El mismo «avión» se modela distinto en un **simulador de vuelo** (interesa el comportamiento de volar) que en una **aplicación de reserva de vuelos** (interesan asientos, horarios y precios).\n\n### Encapsulación\nEs la capacidad de un objeto de **esconder partes de su estado y comportamiento** de otros objetos, exponiendo únicamente una **interfaz limitada** al resto del programa. Así se protegen los datos internos y se reduce el acoplamiento.\n\n### Herencia\nEs la capacidad de **crear nuevas clases sobre otras existentes**. Su principal ventaja es la **reutilización de código**: si necesitas una clase ligeramente diferente a una ya existente, no hay que duplicar el código. En los lenguajes se materializa con palabras clave de unión como `extends`, `:` o el nombre del padre entre paréntesis, con llamadas al constructor superior tipo `super()` o `base()`, y con la **sobrescritura de métodos** (si `Vehiculo` tiene `encender()`, la subclase `Cisterna` puede cambiar o ampliar ese comportamiento).\n\n### Polimorfismo\nPermite que objetos de clases distintas puedan tratarse de forma uniforme a través de una misma interfaz o clase base.\n\n## Jerarquías de clase en la práctica\n\nUn ejemplo clásico es una **Transacción** base que registra monto y moneda, y que se ramifica en tres formas de pago: **Tarjeta** (valida número de plástico y franquicia Visa/Mastercard), **Transferencia** (guarda código de banco y cuenta de origen) y **Cripto** (requiere el hash de la billetera y la red Blockchain).",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/02 - POO.md"
  },
  {
    id: "AP-ASW-02",
    tema: "Relaciones entre Objetos",
    titulo: "De la dependencia a la herencia: cómo se relacionan los objetos",
    contenido: "## Dependencia\nEs la relación **más básica y débil** entre clases. Existe cuando ciertos cambios en la definición de una clase pueden provocar modificaciones en otra. Ocurre normalmente al usar **nombres de clases concretas** en el código: tipos en las firmas de un método, instanciaciones con el constructor, etc. Se puede **debilitar** haciendo que el código dependa de **interfaces o clases abstractas** en lugar de clases concretas.\n\n## Asociación\nEs una relación en la que un objeto **utiliza o interactúa con otro** de forma permanente. En UML se dibuja con una **flecha simple** hacia el objeto que se utiliza; es totalmente normal tener asociaciones **bidireccionales** (flecha con punta en cada extremo). Puede verse como una dependencia especializada: aquí el objeto siempre tiene acceso a los objetos con los que interactúa.\n\n## Agregación\nEs un tipo especializado de asociación que representa relaciones **«uno a muchos», «muchos a muchos» o «todo a parte»**. Un objeto «tiene» un grupo de otros objetos y actúa como **contenedor o colección**. El componente **puede existir sin el contenedor** y puede vincularse a varios contenedores a la vez.\n\n## Composición\nEs un tipo específico de agregación en el que el componente **solo puede existir como parte del contenedor** (relación de «vivir o morir»). En UML se representa como la agregación, pero con un **diamante relleno** en la base de la flecha.\n\n## En resumen\n\n- **Dependencia:** la clase A puede verse afectada por cambios en la clase B.\n- **Asociación:** el objeto A conoce al objeto B.\n- **Agregación:** A conoce a B y consiste en B.\n- **Composición:** A conoce a B, consiste en B y **gestiona su ciclo de vida**.\n- **Implementación:** A define métodos declarados en la interfaz B; los objetos A pueden tratarse como B.\n- **Herencia:** A hereda interfaz e implementación de B, pudiendo extenderlas; el objeto A puede tratarse como B.",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/02 - POO.md"
  },
  {
    id: "AP-ASW-03",
    tema: "Principios de Diseño",
    titulo: "Buen diseño y sus tres principios fundamentales",
    contenido: "## ¿Qué es un buen diseño?\n\n**El cambio es lo único constante** en la vida de un programador: lanzas un videojuego para Windows y piden versión MacOS; haces botones cuadrados y se ponen de moda los redondos; diseñas un comercio electrónico y los clientes quieren pedir por teléfono. De ahí nacen dos características del buen diseño: la **extensibilidad** y la **reutilización de código**, una de las formas más habituales de reducir costos de desarrollo.\n\n## 1er principio: Encapsula lo que varía\n\n**Identifica los aspectos de la aplicación que varían y sepáralos de los que se mantienen inalterables.** Esta separación puede hacerse a nivel de **método** o a nivel de **clase**, aislando así las partes volátiles para que los cambios no contaminen el resto del sistema.\n\n## 2do principio: Programa a una interfaz, no a una implementación\n\n**Depende de abstracciones, no de clases concretas.** Una interface es como **las reglas de un juego**: dice qué acciones debe poder hacer un personaje, pero no dice cómo las hace.\n\nEjemplo clásico: si la clase `Cat` depende directamente de `Sausage`, está acoplada a un alimento concreto. Si en cambio depende de la interfaz `Food`, mañana puedes crear `Fish` o `Meat` que implementen `Food`, y el gato podrá comerlos **sin modificar la clase `Cat`**.\n\n## 3er principio: Favorece la composición sobre la herencia\n\nAnte la duda, es preferible **componer objetos** en lugar de construir jerarquías de herencia profundas: la composición es más flexible y permite cambiar el comportamiento en tiempo de ejecución sin quedar atrapado en una jerarquía rígida.",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/04 - Principios de Diseno de Software.md"
  },
  {
    id: "AP-ASW-04",
    tema: "SOLID",
    titulo: "Los cinco principios SOLID",
    contenido: "## Origen y advertencia\n\nEn **2002**, Robert Martin presentó estos principios en el libro *Desarrollo ágil de software: principios, patrones y prácticas*. **SOLID** es una regla mnemotécnica para cinco principios de diseño ideados para hacer que los diseños sean más **comprensibles, flexibles y fáciles de mantener**. Su uso debe ir acompañado de un **análisis previo**: aplicados de forma descuidada pueden hacer más mal que bien y volver la arquitectura más complicada de lo que debería.\n\n## Los cinco principios\n\n### S — Single Responsibility Principle\nUna clase **solo debe tener una razón para cambiar**. Haz que cada clase sea responsable de una única parte de la funcionalidad y que esa responsabilidad quede totalmente encapsulada (escondida) dentro de la clase.\n\n### O — Open/Closed Principle\nLas clases deben estar **abiertas a la extensión pero cerradas a la modificación**: puedes crear subclases, añadir métodos o campos y sobrescribir el comportamiento base. Algunos lenguajes permiten restringir la extensión con palabras clave como `final`.\n\n### L — Liskov Substitution Principle\nAl extender una clase, debes poder **pasar objetos de las subclases en lugar de objetos de la clase padre sin descomponer el código cliente**. Lo definió **Barbara Liskov** en 1987 en su trabajo *Data abstraction and hierarchy*.\n\n### I — Interface Segregation Principle\n**No fuerces a los clientes a depender de métodos que no utilizan.** Desintegra las interfaces «gruesas» en otras más detalladas y específicas; de lo contrario, un cambio en una interfaz grande descompondrá incluso a clientes que no usan los métodos cambiados.\n\n### D — Dependency Inversion Principle\nLas clases de **alto nivel** (lógica de negocio compleja que ordena hacer cosas) **no deben depender de las de bajo nivel** (operaciones básicas: disco, red, base de datos). **Ambas deben depender de abstracciones**, y los detalles deben depender de las abstracciones, no al revés.",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/05 - Principios SOLID.md"
  },
  {
    id: "AP-ASW-05",
    tema: "Patrones de Diseño",
    titulo: "Qué son los patrones y el patrón Prototype",
    contenido: "## ¿Qué son los patrones de diseño?\n\nSon **soluciones habituales a problemas que ocurren con frecuencia** en el diseño de software. Son como **planos prefabricados** que se pueden personalizar para resolver un problema recurrente. Ojo: **no se pueden copiar al programa como funciones o bibliotecas preparadas**; un patrón no es una porción específica de código, sino un **concepto general** que adaptas a las realidades de tu propio programa.\n\n¿Por qué aprenderlos? Porque son **soluciones comprobadas** y porque definen un **lenguaje común** para comunicar ideas de diseño de forma más eficiente. Se clasifican en creacionales, estructurales y de comportamiento.\n\n## Patrón Prototype (creacional)\n\nPermite **copiar o clonar objetos existentes sin que el código dependa de sus clases concretas**.\n\nImagina un objeto complejo (un personaje de juego con equipamiento, atributos y estado) que quieres duplicar. Es ideal cuando **crear el objeto desde cero es costoso** (cálculos pesados, consultas a base de datos, llamadas a API) o cuando quieres evitar una subclase para cada tipo de objeto.\n\nSi intentas clonarlo **desde fuera**: necesitas conocer todos sus atributos privados para copiar los valores, tu código queda **estrechamente acoplado** a la clase concreta, y si la inicialización toma tiempo, re-ejecutar el constructor con todos sus pasos resulta ineficiente.\n\nLa solución: en lugar de copiar externamente, **el propio objeto se encarga de clonarse a sí mismo**; el original actúa como «prototipo». En **Python**, el módulo nativo `copy` facilita el patrón, en particular con `copy.deepcopy()` para copias profundas de objetos complejos.",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/06 - Patrones de Diseño.md"
  },
  {
    id: "AP-ASW-06",
    tema: "Patrones Estructurales",
    titulo: "Bridge, Composite y Proxy: estructurar clases grandes",
    contenido: "## Bridge\n\nPatrón **estructural** cuyo objetivo es **desacoplar una abstracción de su implementación** para que ambas puedan variar de forma independiente.\n\nMotivación: si tienes formas (`Circulo`, `Cuadrado`) y plataformas de renderizado (`Vector`, `Raster`) y usas herencia directa para cubrir combinaciones, sufres la **explosión de clases**: `CirculoVector`, `CirculoRaster`, `CuadradoVector`, `CuadradoRaster`... y con cada forma o motor nuevo el número de clases se dispara.\n\nSolución: **cambiar la herencia por composición**, dividiendo en dos jerarquías independientes: la **Abstracción** (capa de alto nivel que interactúa con el cliente, p. ej. `Forma`, con una referencia hacia la implementación) y la **Implementación** (capa de bajo nivel que hace el trabajo, p. ej. `Renderizador`).\n\n## Composite\n\nPermite **componer objetos en estructuras de árbol** y trabajar con ellas como si fueran objetos individuales. Útil cuando el dominio es jerárquico: sistema de archivos, menú de navegación, UI.\n\nEn un sistema de archivos hay **Archivos** (PDF, imágenes) y **Carpetas** (vacías o con archivos y otras carpetas). Sin el patrón, calcular el tamaño total exige bucles `if/isinstance` preguntando tipo por tipo. El patrón propone tratar a los elementos simples (**Leaves**) y compuestos (**Composite**) mediante una **interfaz común**: el contenedor recorre a sus hijos y les pide la misma operación; si es archivo devuelve su tamaño, si es carpeta se calcula recursivamente.\n\n## Proxy\n\nProporciona un **sustituto o intermediario** de otro objeto, **controlando el acceso** al original y realizando tareas adicionales (**validación, caché, logs, carga diferida**) antes o después de delegar. El Proxy implementa la **misma interfaz** que el objeto real; el cliente interactúa con él como si fuera el real, y solo cuando es necesario pasa la petición al objeto real (evitando desperdiciar recursos si nunca se usa).",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/07 - Patrones de Diseño - Parte 2.md"
  },
  {
    id: "AP-ASW-07",
    tema: "Patrones de Comportamiento",
    titulo: "Memento, Template Method, Chain of Responsibility e Iterator",
    contenido: "## Memento\n\nPermite **guardar y restaurar el estado anterior** de un objeto **sin revelar su implementación interna** (respeta el encapsulamiento). Es la base de las funciones de **Deshacer (Ctrl+Z)** en editores de texto o herramientas de dibujo.\n\nGuardar el estado copiando campos externamente provocaría **violación de encapsulamiento** (habría que hacer públicos todos los campos) y **código frágil** (cualquier cambio en los atributos rompe el código externo).\n\nDistribuye la responsabilidad en 3 actores: el **Originador** (objeto principal, único que sabe crear un Memento con su estado y restaurarse con él), el **Memento** (objeto inmutable, copia del estado en un momento dado; nadie más debe leerlo ni modificarlo) y el **Cuidador** (guarda la pila/historial de Mementos y decide cuándo guardar o restaurar, sin inspeccionar su contenido).\n\n## Template Method\n\nDefine el **esqueleto de un algoritmo en un método de una clase base**, delegando algunos pasos a las subclases, que redefinen pasos sin cambiar la estructura general. Ejemplo: procesar PDF, DOCX y CSV comparte el flujo **abrir archivo → extraer datos (varía) → analizar → generar reporte → cerrar**. El método plantilla en la clase base abstracta llama a los pasos en orden: unos con implementación predeterminada y otros abstractos que las subclases sobrescriben, evitando duplicar código.\n\n## Chain of Responsibility\n\nPasa las **peticiones a lo largo de una cadena de manejadores**: cada uno decide si la procesa o la pasa al siguiente. Evita el bloque gigante de `if/else` de validaciones (autenticación, permisos, formato, stock); cada verificación se vuelve un **manejador independiente** con interfaz común y referencia al siguiente, facilitando reordenar o añadir verificaciones.\n\n## Iterator\n\nPermite **recorrer los elementos de una colección de forma secuencial sin exponer su estructura interna** (listas, árboles con DFS/BFS, grafos, tablas hash). Extrae el recorrido a un objeto **Iterador** que encapsula posición actual, avance y si quedan elementos, exponiendo una **interfaz estándar** al cliente.",
    fuente: "BancoDeInformacion/ArquitecturaDeSoftware/07 - Patrones de Diseño - Parte 2.md"
  }
];

export default apuntes;
