// Preguntas del track de Python (spec 011). Misma forma que el resto de tracks:
// id único, parcial (etapa), tema, dificultad, tipo (multiple/codigo/dragdrop),
// y explicación didáctica. `claseError`: silencioso, logica, sintaxis.
const preguntas = [
  // ─── Etapa 1 · Fundamentos (corto) ─────────────────────────────────────
  {
    id: "PY-001",
    parcial: "Fundamentos",
    tema: "Sintaxis y tipos",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "x = 5\nx = x + 1\ny = \"5\"\nprint(x + y)",
    options: ["TypeError", "65", "11", "6"],
    correct: 0,
    exp: "Python no convierte tipos implícitamente en `+`: sumar un int con un str lanza TypeError. A diferencia de JavaScript, acá no hay coerción silenciosa; hay que hacer `str(x) + y` o `x + int(y)`.",
    claseError: "logica"
  },
  {
    id: "PY-002",
    parcial: "Fundamentos",
    tema: "Sintaxis y tipos",
    dificultad: "facil",
    tipo: "multiple",
    q: "¿Cuál es el resultado de `7 / 2` en Python 3?",
    options: ["3.5", "3", "3.0", "Error"],
    correct: 0,
    exp: "En Python 3, `/` es división verdadera y siempre devuelve float. La división entera (truncada) es `//`. La IA entrenada en otros lenguajes a veces asume que `/` trunca.",
    claseError: "logica"
  },
  {
    id: "PY-003",
    parcial: "Fundamentos",
    tema: "Sintaxis y tipos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "print(7 // 2, 7 % 2)",
    options: ["3 1", "3.5 1", "3 1.0", "2 3"],
    correct: 0,
    exp: "`//` es división entera (3) y `%` es el resto (1). Como ambos operandos son int, los dos resultados son int.",
    claseError: "logica"
  },
  {
    id: "PY-004",
    parcial: "Fundamentos",
    tema: "Sintaxis y tipos",
    dificultad: "facil",
    tipo: "multiple",
    q: "¿Qué define los bloques de código en Python?",
    options: ["La indentación", "Las llaves {}", "Los paréntesis", "La palabra end"],
    correct: 0,
    exp: "Python usa indentación obligatoria para delimitar bloques. Mezclar tabulaciones y espacios o indentar mal produce IndentationError o, peor, lógica errónea silenciosa.",
    claseError: "sintaxis"
  },
  {
    id: "PY-005",
    parcial: "Fundamentos",
    tema: "Mutabilidad y referencias",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
    options: ["[1, 2, 3, 4]", "[1, 2, 3]", "Error", "[4]"],
    correct: 0,
    exp: "`b = a` no copia la lista: hace que b apunte al mismo objeto. Modificar b modifica a. Para copiar, usá `a[:]`, `a.copy()` o `list(a)`.",
    claseError: "silencioso"
  },
  {
    id: "PY-006",
    parcial: "Fundamentos",
    tema: "Mutabilidad y referencias",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "a = [1, 2, 3]\nb = a[:]\nb.append(4)\nprint(a)",
    options: ["[1, 2, 3]", "[1, 2, 3, 4]", "Error", "[4]"],
    correct: 0,
    exp: "`a[:]` crea una copia superficial de la lista, así que b es un objeto distinto. Modificar b no afecta a a. Ojo: si la lista tuviera sublistas, estas seguirían compartidas.",
    claseError: "logica"
  },
  {
    id: "PY-007",
    parcial: "Fundamentos",
    tema: "Mutabilidad y referencias",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuál de estos tipos es inmutable?",
    options: ["tuple", "list", "dict", "set"],
    correct: 0,
    exp: "Las tuplas no se pueden modificar después de creadas. Listas, dicts y sets sí son mutables. Strings y números también son inmutables.",
    claseError: "logica"
  },
  {
    id: "PY-008",
    parcial: "Fundamentos",
    tema: "Mutabilidad y referencias",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "a = [1, 2]\nb = [1, 2]\nprint(a == b)\nprint(a is b)",
    options: ["True y luego False", "True y luego True", "False y luego False", "Error"],
    correct: 0,
    exp: "`==` compara contenido; `is` compara identidad (si son el mismo objeto). Dos listas creadas por separado tienen el mismo contenido pero son objetos distintos. Para valores, usá siempre `==`.",
    claseError: "silencioso"
  },

  // ─── Etapa 2 · Estructuras de datos ─────────────────────────────────────
  {
    id: "PY-009",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "lista = [1, 2]\nlista.append([3, 4])\nprint(len(lista))",
    options: ["3", "4", "2", "Error"],
    correct: 0,
    exp: "`append` agrega el objeto como un solo elemento: la lista queda [1, 2, [3, 4]] y su largo es 3. Para agregar cada elemento por separado, usá `extend`.",
    claseError: "silencioso"
  },
  {
    id: "PY-010",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "lista = [1, 2]\nlista.extend([3, 4])\nprint(lista)",
    options: ["[1, 2, 3, 4]", "[1, 2, [3, 4]]", "[3, 4]", "Error"],
    correct: 0,
    exp: "`extend` itera el argumento y agrega cada elemento al final. La lista queda [1, 2, 3, 4]. Es la diferencia clave con `append`.",
    claseError: "logica"
  },
  {
    id: "PY-011",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [3, 1, 2]\nresultado = nums.sort()\nprint(resultado)",
    options: ["None", "[1, 2, 3]", "[3, 1, 2]", "Error"],
    correct: 0,
    exp: "`sort()` ordena in-place y devuelve None. Si querés una lista nueva ordenada, usá `sorted(nums)`. Asignar el resultado de `sort()` a una variable es un bug silencioso clásico.",
    claseError: "silencioso"
  },
  {
    id: "PY-012",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [3, 1, 2]\nordenada = sorted(nums)\nprint(nums, ordenada)",
    options: ["[3, 1, 2] [1, 2, 3]", "[1, 2, 3] [1, 2, 3]", "[3, 1, 2] [3, 1, 2]", "Error"],
    correct: 0,
    exp: "`sorted()` devuelve una lista nueva ordenada y no modifica la original. Por eso nums sigue [3, 1, 2] y ordenada es [1, 2, 3].",
    claseError: "logica"
  },
  {
    id: "PY-013",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "media",
    tipo: "multiple",
    q: "Con `t = (1, 2, 3)`, ¿cuál de estas operaciones falla?",
    options: ["t[0] = 5", "t[0]", "len(t)", "t + (4,)"],
    correct: 0,
    exp: "Las tuplas son inmutables: no se puede asignar a un índice. Leer, medir y concatenar (creando una tupla nueva) sí funcionan.",
    claseError: "sintaxis"
  },
  {
    id: "PY-014",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "t = (1, [2, 3])\nt[1].append(4)\nprint(t)",
    options: ["(1, [2, 3, 4])", "TypeError", "(1, [2, 3])", "Error de sintaxis"],
    correct: 0,
    exp: "La tupla es inmutable en sus referencias, pero el objeto lista que contiene sí puede mutar. `t[1].append(4)` modifica la lista interna sin reasignar la tupla.",
    claseError: "silencioso"
  },
  {
    id: "PY-015",
    parcial: "Estructuras de datos",
    tema: "Listas y tuplas",
    dificultad: "media",
    tipo: "dragdrop",
    q: "Completá el desempaquetado para que a=1, b=2 y resto=[3, 4].",
    codigo: "{1}, {2}, {3}resto = [1, 2, 3, 4]",
    piezas: ["a", "b", "*", "&"],
    respuestas: ["a", "b", "*"],
    exp: "El desempaquetado asigna en orden y el operador `*` junta los sobrantes en una lista. `&` no existe en este contexto.",
    claseError: "sintaxis"
  },
  {
    id: "PY-016",
    parcial: "Estructuras de datos",
    tema: "Slicing",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [0, 1, 2, 3, 4]\nprint(nums[1:3])",
    options: ["[1, 2]", "[1, 2, 3]", "[0, 1, 2]", "[2, 3]"],
    correct: 0,
    exp: "El slicing `[inicio:fin]` incluye el inicio y excluye el fin. Por eso nums[1:3] toma los índices 1 y 2: [1, 2].",
    claseError: "logica"
  },
  {
    id: "PY-017",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "d = {\"a\": 1}\nprint(d.get(\"b\"))",
    options: ["None", "KeyError", "0", "b"],
    correct: 0,
    exp: "`get` devuelve None si la clave no existe (o el default que le pases). Es la forma segura de leer un dict sin riesgo de KeyError.",
    claseError: "logica"
  },
  {
    id: "PY-018",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "d = {\"a\": 1}\nprint(d[\"b\"])",
    options: ["KeyError", "None", "0", "Imprime b"],
    correct: 0,
    exp: "Acceder con `d[clave]` a una clave inexistente lanza KeyError. Si la clave puede no estar, usá `d.get(clave, default)` o `defaultdict`.",
    claseError: "sintaxis"
  },
  {
    id: "PY-019",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "d = {}\nd[\"a\"] = 1\nd[\"a\"] = 2\nprint(d)",
    options: ["{'a': 2}", "{'a': 1}", "{'a': 1, 'a': 2}", "Error"],
    correct: 0,
    exp: "Las claves de un dict son únicas: asignar dos veces a la misma clave sobreescribe el valor. El dict queda {'a': 2}.",
    claseError: "logica"
  },
  {
    id: "PY-020",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Los diccionarios de Python mantienen el orden de inserción?",
    options: ["Sí, está garantizado desde Python 3.7", "No, son desordenados", "Ordenan las claves alfabéticamente", "Depende del hash de la clave"],
    correct: 0,
    exp: "Desde Python 3.7 el orden de inserción es parte de la especificación. Antes era un detalle de implementación de CPython 3.6. No confundas con dict ordenado por clave: eso sería `sorted(d)`.",
    claseError: "logica"
  },
  {
    id: "PY-021",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "s = {1, 2, 2, 3}\nprint(len(s))",
    options: ["3", "4", "2", "Error"],
    correct: 0,
    exp: "Un set elimina duplicados al crearse. Quedan {1, 2, 3}, así que el largo es 3.",
    claseError: "logica"
  },
  {
    id: "PY-022",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "x = {}\nprint(type(x))",
    options: ["dict", "set", "tuple", "Error"],
    correct: 0,
    exp: "`{}` crea un dict vacío, no un set. El set vacío se crea con `set()`. Es una trampa clásica porque la sintaxis de set literal usa llaves.",
    claseError: "silencioso"
  },
  {
    id: "PY-023",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Cuál de estos tipos NO puede ser clave de un diccionario?",
    options: ["list", "tuple", "str", "int"],
    correct: 0,
    exp: "Las claves deben ser hashables (inmutables). Las listas son mutables y no tienen hash, así que lanzan TypeError al usarse como clave. Las tuplas sí, si sus elementos también son inmutables.",
    claseError: "sintaxis"
  },
  {
    id: "PY-024",
    parcial: "Estructuras de datos",
    tema: "Diccionarios y sets",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "d = {\"a\": 1, \"b\": 2}\nfor x in d:\n    print(x)",
    options: ["Las claves a y b", "Los valores 1 y 2", "Los pares ('a', 1) y ('b', 2)", "Error"],
    correct: 0,
    exp: "Iterar un dict recorre sus claves. Para recorrer pares clave-valor usá `d.items()`, y para valores `d.values()`.",
    claseError: "logica"
  },
  {
    id: "PY-025",
    parcial: "Estructuras de datos",
    tema: "Comprehensions",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "cuadrados = [n * n for n in range(3)]\nprint(cuadrados)",
    options: ["[0, 1, 4]", "[1, 4, 9]", "[0, 1, 2]", "Error"],
    correct: 0,
    exp: "`range(3)` produce 0, 1, 2. La comprehension eleva al cuadrado cada uno: [0, 1, 4]. Si esperabas [1, 4, 9], pensaste en range(1, 4).",
    claseError: "logica"
  },
  {
    id: "PY-026",
    parcial: "Estructuras de datos",
    tema: "Comprehensions",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "pares = [n for n in range(6) if n % 2 == 0]\nprint(pares)",
    options: ["[0, 2, 4]", "[2, 4, 6]", "[1, 3, 5]", "[0, 2, 4, 6]"],
    correct: 0,
    exp: "`range(6)` va de 0 a 5. El filtro deja los pares: 0, 2, 4. El 6 no entra porque range excluye el extremo.",
    claseError: "logica"
  },
  {
    id: "PY-027",
    parcial: "Estructuras de datos",
    tema: "Comprehensions",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "d = {n: n * 2 for n in range(3)}\nprint(d)",
    options: ["{0: 0, 1: 2, 2: 4}", "[0, 2, 4]", "{0, 2, 4}", "Error"],
    correct: 0,
    exp: "Es una dict comprehension: la parte antes de los dos puntos es la clave y la siguiente el valor. Produce {0: 0, 1: 2, 2: 4}.",
    claseError: "logica"
  },
  {
    id: "PY-028",
    parcial: "Estructuras de datos",
    tema: "Slicing",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [0, 1, 2, 3, 4, 5]\nprint(nums[::2])",
    options: ["[0, 2, 4]", "[1, 3, 5]", "[0, 1]", "[2, 4]"],
    correct: 0,
    exp: "`[::2]` toma toda la lista con paso 2: índices 0, 2, 4. El tercer componente del slicing es el paso.",
    claseError: "logica"
  },
  {
    id: "PY-029",
    parcial: "Estructuras de datos",
    tema: "Slicing",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [1, 2, 3]\nprint(nums[::-1])",
    options: ["[3, 2, 1]", "[1, 2, 3]", "Error", "None"],
    correct: 0,
    exp: "Un paso negativo recorre al revés. `nums[::-1]` es la forma idiomática de invertir una lista, y devuelve una copia nueva.",
    claseError: "logica"
  },
  {
    id: "PY-030",
    parcial: "Estructuras de datos",
    tema: "Slicing",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "matriz = [[1, 2], [3, 4]]\ncopia = [fila[:] for fila in matriz]\ncopia[0][0] = 9\nprint(matriz[0][0])",
    options: ["1", "9", "Error", "None"],
    correct: 0,
    exp: "La comprehension con `fila[:]` copia cada sublista, así que la copia es independiente. Si hubieras hecho `copia = matriz[:]`, las sublistas seguirían compartidas y verías 9.",
    claseError: "silencioso"
  },

  // ─── Etapa 3 · Funciones y POO ─────────────────────────────────────
  {
    id: "PY-031",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def agregar(item, lista=[]):\n    lista.append(item)\n    return lista\n\nprint(agregar(1))\nprint(agregar(2))",
    options: ["[1] y luego [1, 2]", "[1] y luego [2]", "[1, 2] y luego [1, 2]", "Error"],
    correct: 0,
    exp: "El default `[]` se crea una sola vez, al definir la función, y se comparte entre todas las llamadas. La segunda llamada ve la lista de la primera. La forma correcta es `lista=None` y crearla adentro.",
    claseError: "silencioso"
  },
  {
    id: "PY-032",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def f(*args, **kwargs):\n    print(len(args), len(kwargs))\n\nf(1, 2, x=3)",
    options: ["2 1", "3 0", "1 2", "Error"],
    correct: 0,
    exp: "`*args` junta los posicionales (1 y 2 → tupla de largo 2) y `**kwargs` los nombrados (x=3 → dict de largo 1).",
    claseError: "logica"
  },
  {
    id: "PY-033",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "facil",
    tipo: "multiple",
    q: "¿Qué hace `*args` en la firma de una función?",
    options: ["Junta los argumentos posicionales sobrantes en una tupla", "Desempaqueta un diccionario", "Define argumentos obligatorios", "Multiplica los argumentos"],
    correct: 0,
    exp: "`*args` captura los posicionales extra en una tupla. Su par para nombrados es `**kwargs`, que captura en un dict.",
    claseError: "logica"
  },
  {
    id: "PY-034",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def f(a, *, b):\n    return a + b\n\nprint(f(1, b=2))",
    options: ["3", "TypeError", "12", "Error de sintaxis"],
    correct: 0,
    exp: "El `*` en la firma marca que lo que sigue es solo por keyword. `f(1, b=2)` es válido y devuelve 3. Llamar `f(1, 2)` daría TypeError.",
    claseError: "logica"
  },
  {
    id: "PY-035",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def f(a, b, c):\n    return a + b + c\n\nnums = [1, 2, 3]\nprint(f(*nums))",
    options: ["6", "TypeError", "[1, 2, 3]", "123"],
    correct: 0,
    exp: "`*nums` desempaqueta la lista en tres argumentos posicionales: a=1, b=2, c=3. La suma es 6.",
    claseError: "logica"
  },
  {
    id: "PY-036",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def f(a, b):\n    return a * b\n\nd = {\"a\": 3, \"b\": 4}\nprint(f(**d))",
    options: ["12", "TypeError", "{'a': 3, 'b': 4}", "7"],
    correct: 0,
    exp: "`**d` desempaqueta el dict como argumentos por nombre: a=3, b=4. El producto es 12. Las claves del dict deben coincidir con los parámetros.",
    claseError: "logica"
  },
  {
    id: "PY-037",
    parcial: "Funciones y POO",
    tema: "Funciones y argumentos",
    dificultad: "media",
    tipo: "multiple",
    q: "Una función con `return 1, 2`, ¿qué devuelve realmente?",
    options: ["Una tupla (1, 2)", "Dos valores independientes", "Una lista [1, 2]", "Un dict {1: 2}"],
    correct: 0,
    exp: "Python empaqueta los valores separados por comas en una tupla. El desempaquetado `a, b = f()` es azúcar sintáctica sobre esa tupla.",
    claseError: "logica"
  },
  {
    id: "PY-038",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "funcs = [lambda: i for i in range(3)]\nprint([f() for f in funcs])",
    options: ["[2, 2, 2]", "[0, 1, 2]", "[0, 0, 0]", "Error"],
    correct: 0,
    exp: "Las lambdas capturan la variable `i` por referencia, no su valor. Cuando se llaman, el loop ya terminó e i vale 2, así que todas devuelven 2. Es el late binding clásico.",
    claseError: "silencioso"
  },
  {
    id: "PY-039",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "funcs = [lambda i=i: i for i in range(3)]\nprint([f() for f in funcs])",
    options: ["[0, 1, 2]", "[2, 2, 2]", "TypeError", "Error"],
    correct: 0,
    exp: "El default `i=i` evalúa el valor de i en cada iteración y lo congela como default de esa lambda. Así cada una recuerda su propio valor: [0, 1, 2].",
    claseError: "logica"
  },
  {
    id: "PY-040",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def deco(f):\n    def wrapper():\n        print(\"antes\")\n        f()\n    return wrapper\n\n@deco\ndef hola():\n    print(\"hola\")\n\nhola()",
    options: ["antes y luego hola", "solo hola", "solo antes", "Error"],
    correct: 0,
    exp: "El decorador reemplaza `hola` por `wrapper`. Al llamar `hola()` se ejecuta wrapper, que imprime \"antes\" y luego llama a la función original.",
    claseError: "logica"
  },
  {
    id: "PY-041",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Qué es un decorador en Python?",
    options: ["Una función que recibe otra y devuelve una nueva extendiendo su comportamiento", "Una clase especial del lenguaje", "Un comentario de documentación", "Una función que se ejecuta al importar el módulo"],
    correct: 0,
    exp: "Un decorador es una función que toma una función y devuelve otra (generalmente un wrapper). La sintaxis `@deco` equivale a `f = deco(f)`.",
    claseError: "logica"
  },
  {
    id: "PY-042",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Qué problema evita `@functools.wraps(f)` dentro de un decorador?",
    options: ["Que la función decorada pierda su nombre, docstring y metadatos", "Que el decorador se ejecute dos veces", "Que la función no devuelva nada", "Nada: es decorativo"],
    correct: 0,
    exp: "Sin wraps, la función decorada pasa a llamarse \"wrapper\" y pierde su __doc__. `functools.wraps` copia los metadatos de la función original al wrapper.",
    claseError: "silencioso"
  },
  {
    id: "PY-043",
    parcial: "Funciones y POO",
    tema: "Closures y decoradores",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def doble(f):\n    def wrapper(*args, **kwargs):\n        return f(*args, **kwargs) * 2\n    return wrapper\n\n@doble\ndef suma(a, b):\n    return a + b\n\nprint(suma(2, 3))",
    options: ["10", "5", "TypeError", "25"],
    correct: 0,
    exp: "El wrapper reenvía los argumentos a `suma` (que da 5) y multiplica el resultado por 2: 10. Por eso los wrappers usan *args y **kwargs: para aceptar cualquier firma.",
    claseError: "logica"
  },
  {
    id: "PY-044",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Punto:\n    def __init__(self, x):\n        self.x = x\n\np = Punto(5)\nprint(p.x)",
    options: ["5", "None", "Error", "x"],
    correct: 0,
    exp: "`__init__` inicializa la instancia: guarda 5 en el atributo self.x. Al crear Punto(5), Python pasa la instancia nueva como primer argumento.",
    claseError: "logica"
  },
  {
    id: "PY-045",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "facil",
    tipo: "multiple",
    q: "¿Qué es `self` en un método de clase?",
    options: ["La instancia actual, pasada como primer argumento", "Una palabra reservada del lenguaje", "El nombre de la clase", "Un puntero nulo"],
    correct: 0,
    exp: "`self` es la instancia sobre la que se llamó el método. No es reservada: es convención; Python la pasa automáticamente al llamar desde la instancia.",
    claseError: "logica"
  },
  {
    id: "PY-046",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Contador:\n    total = 0\n    def __init__(self):\n        Contador.total += 1\n\na = Contador()\nb = Contador()\nprint(Contador.total)",
    options: ["2", "1", "0", "Error"],
    correct: 0,
    exp: "`total` es un atributo de clase compartido. Cada __init__ lo incrementa vía la clase, así que tras dos instancias vale 2.",
    claseError: "logica"
  },
  {
    id: "PY-047",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Caja:\n    items = []\n    def agregar(self, x):\n        self.items.append(x)\n\na = Caja()\nb = Caja()\na.agregar(1)\nprint(b.items)",
    options: ["[1]", "[]", "Error", "None"],
    correct: 0,
    exp: "`items` es un atributo de clase mutable compartido por todas las instancias. `self.items.append` muta la lista de la clase, no una lista por instancia. b ve el 1. El fix es crear self.items = [] en __init__.",
    claseError: "silencioso"
  },
  {
    id: "PY-048",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Saludo:\n    def hola(self):\n        return \"hola\"\n\ns = Saludo()\nprint(s.hola())",
    options: ["hola", "TypeError: falta self", "None", "Error"],
    correct: 0,
    exp: "Al llamar desde la instancia, Python pasa `s` como self automáticamente. No hay que pasarlo a mano; por eso la firma lo declara pero la llamada no lo incluye.",
    claseError: "logica"
  },
  {
    id: "PY-049",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Qué método especial inicializa los atributos de una instancia recién creada?",
    options: ["__init__", "__create__", "__call__", "__new__ solamente"],
    correct: 0,
    exp: "`__init__` recibe la instancia ya creada y la inicializa. (`__new__` crea el objeto, pero casi nunca se sobreescribe; `__call__` hace a la instancia llamable.)",
    claseError: "logica"
  },
  {
    id: "PY-050",
    parcial: "Funciones y POO",
    tema: "Clases y self",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Punto:\n    def __init__(self, x):\n        self.x = x\n    def __str__(self):\n        return f\"Punto({self.x})\"\n\np = Punto(3)\nprint(p)",
    options: ["Punto(3)", "<__main__.Punto object>", "3", "Error"],
    correct: 0,
    exp: "`print` usa `__str__` si está definido. Sin él, verías la representación genérica del objeto. `__repr__` es la versión para debugging.",
    claseError: "logica"
  },
    // ─── Etapa 3 · Funciones y POO (continuación: herencia y dunders) ───────
  {
    id: "PY-051",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class A:\n    def __init__(self):\n        self.x = 1\n\nclass B(A):\n    def __init__(self):\n        super().__init__()\n        self.y = 2\n\nb = B()\nprint(b.x, b.y)",
    options: ["1 2", "AttributeError", "None None", "Error de sintaxis"],
    correct: 0,
    exp: "`super().__init__()` ejecuta el inicializador de A, que crea x; luego B agrega y. Por eso la instancia tiene ambos atributos.",
    claseError: "logica"
  },
  {
    id: "PY-052",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "class A:\n    def __init__(self):\n        self.x = 1\n\nclass B(A):\n    def __init__(self):\n        self.y = 2\n\nb = B()\nprint(b.x)",
    options: ["AttributeError", "Imprime 1", "Imprime None", "Imprime 0"],
    correct: 0,
    exp: "Al definir `__init__` en B sin llamar a `super().__init__()`, el de A nunca se ejecuta y x no existe. Es un bug silencioso típico cuando la IA sobreescribe inicializadores.",
    claseError: "silencioso"
  },
  {
    id: "PY-053",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "media",
    tipo: "multiple",
    q: "Con herencia múltiple, ¿en qué orden busca Python los métodos?",
    options: ["En el MRO (method resolution order), de izquierda a derecha", "Alfabético", "Siempre gana el último definido", "Aleatorio según el hash"],
    correct: 0,
    exp: "Python linealiza la jerarquía con el algoritmo C3 y produce el MRO, que podés inspeccionar con `Clase.__mro__`. En `class C(A, B)`, busca en C, luego A, luego B.",
    claseError: "logica"
  },
  {
    id: "PY-054",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class A: pass\nclass B(A): pass\n\nb = B()\nprint(isinstance(b, A), type(b) is A)",
    options: ["True False", "True True", "False False", "False True"],
    correct: 0,
    exp: "`isinstance` considera la herencia: b es instancia de B y por lo tanto de A. `type(b) is A` compara la clase exacta, que es B, así que da False.",
    claseError: "logica"
  },
  {
    id: "PY-055",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Circulo:\n    def __init__(self, r):\n        self._r = r\n    @property\n    def radio(self):\n        return self._r\n\nc = Circulo(2)\nprint(c.radio)",
    options: ["2", "TypeError", "<property object>", "None"],
    correct: 0,
    exp: "`@property` expone el método como atributo de solo lectura: se accede sin paréntesis. Intentar `c.radio = 5` daría AttributeError porque no hay setter.",
    claseError: "logica"
  },
  {
    id: "PY-056",
    parcial: "Funciones y POO",
    tema: "Herencia y dunders",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Qué método especial hay que implementar para que `==` compare contenido en una clase propia?",
    options: ["__eq__", "__cmp__", "__equals__", "__same__"],
    correct: 0,
    exp: "Sin `__eq__`, `==` compara identidad como si fuera `is`. `__cmp__` es de Python 2 y `__equals__` no existe. Definí `__eq__` y, si querés usarlas en sets o dicts, también `__hash__`.",
    claseError: "sintaxis"
  },

  // ─── Etapa 4 · Errores, generators y concurrencia ───────────────────────
  {
    id: "PY-057",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "facil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "try:\n    x = 1 / 0\nexcept ZeroDivisionError:\n    print(\"A\")\nexcept Exception:\n    print(\"B\")",
    options: ["A", "B", "A y B", "Error"],
    correct: 0,
    exp: "Se ejecuta solo el primer `except` que coincide con el tipo de la excepción. ZeroDivisionError es más específico que Exception, así que gana el primero. El orden de los except importa.",
    claseError: "logica"
  },
  {
    id: "PY-058",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "media",
    tipo: "dragdrop",
    q: "Completá las cláusulas en el orden correcto.",
    codigo: "try:\n    x = 1\n{1} Exception:\n    print(\"error\")\n{2}:\n    print(\"ok\")\n{3}:\n    print(\"fin\")",
    piezas: ["except", "else", "finally", "catch"],
    respuestas: ["except", "else", "finally"],
    exp: "`except` captura la excepción, `else` se ejecuta solo si no hubo ninguna, y `finally` siempre. `catch` no existe en Python: es de otros lenguajes.",
    claseError: "sintaxis"
  },
  {
    id: "PY-059",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Por qué es peligroso `except Exception: pass`?",
    options: ["Oculta errores reales y hace casi imposible depurar", "Es más lento que un except específico", "No compila", "No tiene ningún problema"],
    correct: 0,
    exp: "Un except amplio que no hace nada traga errores de programación, KeyboardInterrupt incluido en el caso de `except: pass`. Capturá el tipo específico y, como mínimo, logueá.",
    claseError: "silencioso"
  },
  {
    id: "PY-060",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def dividir(a, b):\n    if b == 0:\n        raise ValueError(\"b no puede ser 0\")\n    return a / b\n\ntry:\n    dividir(1, 0)\nexcept ValueError as e:\n    print(e)",
    options: ["b no puede ser 0", "ValueError", "0", "Error"],
    correct: 0,
    exp: "`raise` lanza la excepción con su mensaje; `except ... as e` la captura y `print(e)` muestra el mensaje pasado al constructor.",
    claseError: "logica"
  },
  {
    id: "PY-061",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "with open(\"f.txt\") as f:\n    contenido = f.read()\nprint(f.closed)",
    options: ["True", "False", "Error", "None"],
    correct: 0,
    exp: "Al salir del bloque `with`, el context manager cierra el archivo automáticamente, incluso si hubo una excepción adentro. Por eso f.closed es True.",
    claseError: "logica"
  },
  {
    id: "PY-062",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Qué métodos debe implementar un context manager propio?",
    options: ["__enter__ y __exit__", "__open__ y __close__", "__with__ y __end__", "__start__ y __stop__"],
    correct: 0,
    exp: "`with` llama a `__enter__` al entrar (su retorno se asigna a la variable del as) y a `__exit__` al salir, que recibe la excepción si la hubo.",
    claseError: "sintaxis"
  },
  {
    id: "PY-063",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def f():\n    try:\n        return 1\n    finally:\n        return 2\n\nprint(f())",
    correct: 0,
    options: ["2", "1", "Error", "None"],
    exp: "Un `return` dentro de `finally` pisa cualquier return o excepción pendiente del try. La función devuelve 2 y el 1 se pierde. Es un bug silencioso clásico.",
    claseError: "silencioso"
  },
  {
    id: "PY-064",
    parcial: "Errores, generators y concurrencia",
    tema: "Excepciones y context managers",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "try:\n    try:\n        raise ValueError(\"interno\")\n    except ValueError:\n        raise KeyError(\"externo\")\nexcept KeyError as e:\n    print(e.__cause__)",
    options: ["None", "ValueError interno", "KeyError externo", "Error"],
    correct: 0,
    exp: "Sin `raise ... from ...`, la excepción nueva no registra causa: `__cause__` queda None (el contexto sí guarda la interna en `__context__`). Para encadenar explícitamente usá `raise KeyError(\"externo\") from e`.",
    claseError: "silencioso"
  },
  {
    id: "PY-065",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def gen():\n    print(\"inicio\")\n    yield 1\n    print(\"medio\")\n    yield 2\n\ng = gen()\nprint(\"creado\")",
    options: ["solo creado", "inicio y luego creado", "inicio, medio y creado", "Error"],
    correct: 0,
    exp: "Llamar a una función con `yield` no ejecuta su cuerpo: solo crea el generator. El código corre recién al pedir el primer valor con `next()` o un for.",
    claseError: "silencioso"
  },
  {
    id: "PY-066",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def gen():\n    yield 1\n    yield 2\n\ng = gen()\nprint(next(g), next(g))",
    options: ["1 2", "1 1", "2 2", "StopIteration"],
    correct: 0,
    exp: "Cada `next()` avanza el generator hasta el siguiente `yield`. El primero devuelve 1 y el segundo 2. Un tercer next lanzaría StopIteration.",
    claseError: "logica"
  },
  {
    id: "PY-067",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def gen():\n    yield 1\n\ng = gen()\nlist(g)\nprint(list(g))",
    options: ["[]", "[1]", "StopIteration", "Error"],
    correct: 0,
    exp: "Los generators se agotan: después de recorrerlos una vez no producen más valores. La segunda pasada da una lista vacía. Si necesitás reutilizar, guardá una lista.",
    claseError: "silencioso"
  },
  {
    id: "PY-068",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuál es la diferencia entre una list comprehension y una generator expression?",
    options: ["La generator expression produce valores bajo demanda sin construir la lista en memoria", "La generator expression es siempre más rápida", "No hay diferencia", "La list comprehension es perezosa"],
    correct: 0,
    exp: "Con corchetes se construye la lista completa; con paréntesis se crea un generator que evalúa de a uno. Para secuencias grandes o pipelines, la generator expression ahorra memoria.",
    claseError: "logica"
  },
  {
    id: "PY-069",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "total = sum(n * n for n in range(4))\nprint(total)",
    options: ["14", "30", "[0, 1, 4, 9]", "Error"],
    correct: 0,
    exp: "Es una generator expression dentro de `sum`: 0 + 1 + 4 + 9 = 14. No hace falta el corchete extra cuando el argumento es único.",
    claseError: "logica"
  },
  {
    id: "PY-070",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "def acumulador():\n    total = 0\n    while True:\n        valor = yield total\n        if valor is None:\n            break\n        total += valor\n\na = acumulador()\nnext(a)\na.send(5)\nprint(a.send(3))",
    options: ["8", "5", "3", "Error"],
    correct: 0,
    exp: "`send()` inyecta un valor en el `yield` pausado. Tras arrancar con next, send(5) acumula 5 y send(3) acumula 3 más: el generator yield-ea 8.",
    claseError: "logica"
  },
  {
    id: "PY-071",
    parcial: "Errores, generators y concurrencia",
    tema: "Generators e iteradores",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Qué métodos debe implementar un iterador propio?",
    options: ["__iter__ y __next__", "__next__ solamente", "__iter__ solamente", "__getitem__ y __len__"],
    correct: 0,
    exp: "Un iterador implementa `__next__` (devuelve el valor o lanza StopIteration) y `__iter__` que se devuelve a sí mismo. Un iterable, en cambio, solo necesita `__iter__`.",
    claseError: "sintaxis"
  },
  {
    id: "PY-072",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Qué limita el GIL (Global Interpreter Lock) en CPython?",
    options: ["Que varios threads ejecuten bytecode Python en paralelo en varios núcleos", "El uso de multiprocessing", "La creación de threads", "El uso de asyncio"],
    correct: 0,
    exp: "El GIL hace que un solo thread ejecute bytecode a la vez. Por eso threading sirve para I/O (esperas) pero no para paralelizar CPU; para eso está multiprocessing.",
    claseError: "logica"
  },
  {
    id: "PY-073",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuándo conviene multiprocessing por sobre threading en CPython?",
    options: ["En tareas intensivas en CPU", "En tareas de I/O y red", "Siempre", "Nunca"],
    correct: 0,
    exp: "Multiprocessing crea procesos con memoria separada, esquivando el GIL y usando varios núcleos de verdad. Para I/O, threading o asyncio son más livianos.",
    claseError: "logica"
  },
  {
    id: "PY-074",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "media",
    tipo: "dragdrop",
    q: "Completá el ciclo de vida básico de un thread.",
    codigo: "t = threading.{1}(target=tarea)\nt.{2}()\nt.{3}()",
    piezas: ["Thread", "start", "join", "run"],
    respuestas: ["Thread", "start", "join"],
    exp: "Se crea el Thread, `start()` lo lanza en paralelo y `join()` espera a que termine. Llamar `run()` directamente ejecutaría la tarea en el hilo actual, sin paralelismo.",
    claseError: "sintaxis"
  },
  {
    id: "PY-075",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué puede imprimir este código?",
    codigo: "import threading\n\ncontador = 0\ndef incrementar():\n    global contador\n    for _ in range(100000):\n        contador += 1\n\nhilos = [threading.Thread(target=incrementar) for _ in range(4)]\n[h.start() for h in hilos]\n[h.join() for h in hilos]\nprint(contador)",
    options: ["Puede ser menos de 400000", "Siempre 400000", "Error", "Siempre 0"],
    correct: 0,
    exp: "`contador += 1` no es atómico (lee, suma, escribe). Sin lock, dos threads pueden pisarse y perder incrementos: condición de carrera. Usá `threading.Lock` o una estructura sincronizada.",
    claseError: "silencioso"
  },
  {
    id: "PY-076",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "import asyncio\n\nasync def main():\n    print(\"a\")\n    await asyncio.sleep(0)\n    print(\"b\")\n\nasyncio.run(main())",
    options: ["a y luego b", "b y luego a", "solo a", "Error"],
    correct: 0,
    exp: "La corrutina imprime \"a\", cede el control con await (aunque sea sleep(0)) y al retomarse imprime \"b\". El orden se mantiene porque no hay otra tarea compitiendo.",
    claseError: "logica"
  },
  {
    id: "PY-077",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "import asyncio\n\nasync def tarea(n):\n    await asyncio.sleep(0.1)\n    return n * 2\n\nasync def main():\n    resultados = await asyncio.gather(tarea(1), tarea(2))\n    print(resultados)\n\nasyncio.run(main())",
    options: ["[2, 4]", "[1, 2]", "4", "Error"],
    correct: 0,
    exp: "`gather` programa las corrutinas en concurrencia y devuelve sus resultados en el orden en que se pasaron, no en el orden en que terminan: [2, 4].",
    claseError: "logica"
  },
  {
    id: "PY-078",
    parcial: "Errores, generators y concurrencia",
    tema: "Threading y asyncio",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Qué pasa si llamás a una corrutina sin `await`?",
    options: ["No se ejecuta y Python avisa con un RuntimeWarning", "Se ejecuta igual de forma sincronica", "Error de sintaxis", "Bloquea el event loop"],
    correct: 0,
    exp: "Llamar a `async def` sin await solo crea el objeto coroutine, que nunca corre; al destruirse, Python emite 'coroutine was never awaited'. Es el bug silencioso más común de asyncio.",
    claseError: "silencioso"
  },

  // ─── Etapa 5 · Auditoría de código Python generado por IA ───────────────
  {
    id: "PY-079",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nums = [2, 4, 6]\nfor n in nums:\n    if n % 2 == 0:\n        nums.remove(n)\nprint(nums)",
    options: ["[4]", "[]", "[2, 4, 6]", "Error"],
    correct: 0,
    exp: "Mutar la lista mientras la recorrés desalinea el iterador: al remover 2, el 4 pasa al índice 0 y el cursor salta al 6; al remover 6, el 4 queda sin evaluarse. Recorré una copia o usá una comprehension.",
    claseError: "silencioso"
  },
  {
    id: "PY-080",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué problema tiene este código generado por IA?",
    codigo: "resultado = \"\"\nfor i in range(1000):\n    resultado += str(i)",
    options: ["Es ineficiente: los strings son inmutables y cada += copia todo; usá \"\".join()", "Error de sintaxis", "No tiene ningún problema", "Pierde datos en cada iteración"],
    correct: 0,
    exp: "Como los strings son inmutables, cada `+=` construye un string nuevo copiando el anterior: complejidad cuadrática. Lo idiomático es juntar partes en una lista y hacer `\"\".join(partes)`.",
    claseError: "logica"
  },
  {
    id: "PY-081",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "x = None\nif x == None:\n    print(\"A\")\nif x is None:\n    print(\"B\")",
    options: ["A y B, pero la guía de estilo pide is None", "solo A", "solo B", "Error"],
    correct: 0,
    exp: "Ambas comparaciones funcionan con None, pero el PEP 8 exige `is None`: `==` depende de __eq__ y puede dar sorpresas con objetos que lo sobreescriben.",
    claseError: "logica"
  },
  {
    id: "PY-082",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "import copy\noriginal = [[1, 2], [3, 4]]\ncopia = copy.copy(original)\ncopia[0][0] = 9\nprint(original[0][0])",
    options: ["9", "1", "Error", "None"],
    correct: 0,
    exp: "`copy.copy` es superficial: copia la lista externa pero las sublistas se comparten. Modificar copia[0][0] toca el original. Para anidados independientes, `copy.deepcopy`.",
    claseError: "silencioso"
  },
  {
    id: "PY-083",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "nombre = \"Ana\"\nprint(f\"Hola {nombre.upper()}\")",
    options: ["Hola ANA", "Hola nombre.upper()", "Error", "Hola {Ana}"],
    correct: 0,
    exp: "Dentro de las llaves de un f-string va cualquier expresión válida, incluidos métodos. Se evalúa al formatear: Hola ANA.",
    claseError: "logica"
  },
  {
    id: "PY-084",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "valores = [0, \"\", [], None]\nvacios = [v for v in valores if not v]\nprint(len(vacios))",
    options: ["4", "0", "1", "Error"],
    correct: 0,
    exp: "0, \"\", [] y None son todos falsy, así que `not v` los deja pasar: 4 elementos. El bug de IA típico es validar solo con `v is None` o `len(v) == 0` y perder casos.",
    claseError: "silencioso"
  },
  {
    id: "PY-085",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "media",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "nums = [10, 20, 30]\nfor i in range(len(nums) + 1):\n    print(nums[i])",
    options: ["IndexError en la última iteración", "Imprime 10 20 30", "Imprime 10 20 30 y None", "Error de sintaxis"],
    correct: 0,
    exp: "`range(len(nums) + 1)` genera índices 0 a 3, pero el último válido es 2. En i=3, nums[3] lanza IndexError. Off-by-one clásico; mejor `for n in nums` o `enumerate`.",
    claseError: "silencioso"
  },
  {
    id: "PY-086",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "contador = 0\ndef incrementar():\n    contador += 1\n\nincrementar()",
    options: ["UnboundLocalError", "contador queda en 1", "TypeError", "No pasa nada"],
    correct: 0,
    exp: "Al asignar `contador` dentro de la función, Python la trata como variable local; como no se le asignó antes de leerla, lanza UnboundLocalError. Para tocar la global hay que declararla con `global`.",
    claseError: "silencioso"
  },
  {
    id: "PY-087",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Bugs silenciosos",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "class Config:\n    def __init__(self):\n        self.modo = \"rapido\"\n    def opciones(self):\n        return [lambda: self.modo for _ in range(2)]\n\nc = Config()\nc.modo = \"lento\"\nprint([f() for f in c.opciones()])",
    options: ["['lento', 'lento']", "['rapido', 'rapido']", "Error", "['rapido', 'lento']"],
    correct: 0,
    exp: "Las lambdas leen `self.modo` en el momento de la llamada, no en el de la creación. Como el modo cambió antes de llamarlas, todas ven \"lento\". Misma raíz que el late binding de PY-038.",
    claseError: "silencioso"
  },
  {
    id: "PY-088",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuál de estos métodos NO existe en las listas de Python?",
    options: ["lista.add(1)", "lista.append(1)", "lista.extend([1])", "lista.insert(0, 1)"],
    correct: 0,
    exp: "`add` es de los sets. En listas existen append, extend e insert. La IA mezcla las APIs de set y list porque ambas son 'colecciones'.",
    claseError: "silencioso"
  },
  {
    id: "PY-089",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuál de estas formas NO existe para buscar en un string?",
    options: ["s.contains(\"a\")", "\"a\" in s", "s.find(\"a\")", "s.startswith(\"a\")"],
    correct: 0,
    exp: "Python no tiene `contains` como método: la membresía se expresa con el operador `in`. `find` devuelve el índice o -1; `contains` es de otros lenguajes.",
    claseError: "silencioso"
  },
  {
    id: "PY-090",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "media",
    tipo: "multiple",
    q: "¿Cuál de estas expresiones NO es válida en Python?",
    options: ["lista.length()", "len(lista)", "lista.__len__()", "len(\"texto\")"],
    correct: 0,
    exp: "El largo se pide con la función built-in `len()`, que internamente llama al dunder `__len__`. `length()` es de JavaScript/Java y no existe acá.",
    claseError: "silencioso"
  },
  {
    id: "PY-091",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Cuál de estas llamadas NO funciona en Python 3?",
    options: ["d.has_key(\"a\")", "\"a\" in d", "d.get(\"a\")", "d.keys()"],
    correct: 0,
    exp: "`has_key` era de Python 2 y se eliminó en Python 3. La forma actual es `\"a\" in d`. La IA entrenada con código viejo todavía lo sugiere.",
    claseError: "silencioso"
  },
  {
    id: "PY-092",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Cuál de estas llamadas NO existe?",
    options: ["math.random()", "random.random()", "math.sqrt(4)", "math.floor(1.5)"],
    correct: 0,
    exp: "El azar vive en el módulo `random`, no en `math`. `math.random()` lanza AttributeError. La IA los confunde porque en JavaScript Math.random sí existe.",
    claseError: "silencioso"
  },
  {
    id: "PY-093",
    parcial: "Auditoría de código Python generado por IA",
    tema: "APIs inventadas",
    dificultad: "dificil",
    tipo: "multiple",
    q: "¿Cuál de estas llamadas NO existe para unir rutas?",
    options: ["path.join(\"a\", \"b\")", "os.path.join(\"a\", \"b\")", "Path(\"a\") / \"b\"", "os.sep"],
    correct: 0,
    exp: "No hay un módulo `path` con `join`: es `os.path.join` o el operador `/` de pathlib. `path.join` es la API de Node.js, y la IA la trae cruzada.",
    claseError: "silencioso"
  },
  {
    id: "PY-094",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "usuarios = [(\"Ana\", 30), (\"Luis\", 25)]\nordenados = sorted(usuarios, key=lambda u: u[2])",
    options: ["IndexError: las tuplas solo tienen índices 0 y 1", "Ordena por nombre", "Ordena por edad", "TypeError"],
    correct: 0,
    exp: "La key accede a u[2], que no existe en tuplas de dos elementos. Para ordenar por edad sería u[1]. Off-by-one en la key: bug frecuente cuando la IA infiere la estructura de datos.",
    claseError: "silencioso"
  },
  {
    id: "PY-095",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "edades = {\"Ana\": 30}\nedad = edades.get(\"Luis\", None) + 1",
    options: ["TypeError: no se puede sumar None con un int", "KeyError", "Devuelve 1", "Devuelve None"],
    correct: 0,
    exp: "`get` con default None devuelve None para una clave ausente, y None + 1 lanza TypeError. Si el default correcto es numérico, usá `get(\"Luis\", 0)`, o validá antes.",
    claseError: "silencioso"
  },
  {
    id: "PY-096",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "media",
    tipo: "codigo",
    q: "Con entrada \"25\", ¿qué pasa al ejecutar este código?",
    codigo: "edad = input(\"Edad: \")\nprint(edad + 1)",
    options: ["TypeError: input devuelve str y no se suma con int", "Imprime 26", "Imprime 251", "Error de sintaxis"],
    correct: 0,
    exp: "`input` siempre devuelve string. Sumarle un int lanza TypeError. Hay que convertir con `int(edad)` (y manejar ValueError si el usuario no escribe un número).",
    claseError: "silencioso"
  },
  {
    id: "PY-097",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "print(0.1 + 0.2 == 0.3)",
    options: ["False", "True", "Error", "0.3"],
    correct: 0,
    exp: "Los floats no representan 0.1 ni 0.2 exactamente: la suma da 0.30000000000000004. Para comparar floats usá `math.isclose(a, b)` o un epsilon.",
    claseError: "silencioso"
  },
  {
    id: "PY-098",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué imprime este código?",
    codigo: "handlers = []\nfor nombre in [\"a\", \"b\"]:\n    handlers.append(lambda: nombre)\nprint([h() for h in handlers])",
    options: ["['b', 'b']", "['a', 'b']", "['a', 'a']", "Error"],
    correct: 0,
    exp: "Las dos lambdas comparten la misma variable `nombre` del closure. Al llamarlas, el loop ya terminó y nombre vale \"b\": ambas devuelven \"b\". Fix: `lambda nombre=nombre: nombre`.",
    claseError: "silencioso"
  },
  {
    id: "PY-099",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué pasa al ejecutar este código?",
    codigo: "with open(\"f.txt\") as f:\n    pass\nprint(f.read())",
    options: ["ValueError: operación de I/O sobre archivo cerrado", "Imprime el contenido", "NameError", "Imprime None"],
    correct: 0,
    exp: "Fuera del `with` el archivo ya está cerrado, así que leerlo lanza ValueError. La IA a veces saca el uso del recurso fuera del bloque que lo gestiona.",
    claseError: "silencioso"
  },
  {
    id: "PY-100",
    parcial: "Auditoría de código Python generado por IA",
    tema: "Auditoría en acción",
    dificultad: "dificil",
    tipo: "codigo",
    q: "¿Qué riesgo tiene este código generado por IA en producción?",
    codigo: "def retirar(saldo, monto):\n    assert monto <= saldo, \"sin saldo\"\n    return saldo - monto",
    options: ["Los assert se eliminan con python -O y la validación desaparece", "assert es más lento que un if", "No compila en producción", "Ninguno: es la forma correcta"],
    correct: 0,
    exp: "Los `assert` son para invariantes de desarrollo: con el flag -O se quitan del bytecode. Para validar entrada de usuario hay que usar `if` con `raise ValueError` explícito.",
    claseError: "silencioso"
  }
];

export default preguntas;

